<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Registration</name>
   <tag></tag>
   <elementGuidId>beea018a-e892-4345-af5c-ae63e36ec6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='registration-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registration-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e97d9d7a-c5d8-4163-af5e-8ff7efb9478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-link</value>
      <webElementGuid>8577ab4f-d4a9-4379-a6c7-9aaafba76f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/simple-blog/redirect/registration;jsessionid=0SAHbFgQpgS9mu_PQTKvECVmJyGGRv3gV_dzapWQlefWsDvFBnZy!-402322966</value>
      <webElementGuid>86701cf7-30f0-4019-883f-9145a072ec95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registration</value>
      <webElementGuid>ef64e8e2-a772-4f75-bb75-41e7fb8f3d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-link&quot;)</value>
      <webElementGuid>872ea04d-ebcb-4c56-8799-0564369dc707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='registration-link']</value>
      <webElementGuid>46749352-8f99-4024-8064-ea45339fa323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Registration')]</value>
      <webElementGuid>d1e34d50-87e6-49fe-979d-de31bf808b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>ffbd383a-811e-46e8-bb5d-836ea12f70e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::a[1]</value>
      <webElementGuid>cce6b701-cd8a-4e72-ab08-6fbea57dde8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'registration-link', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>f0903d52-0aed-42a0-a3eb-c904bd8d25d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/simple-blog/redirect/registration;jsessionid=0SAHbFgQpgS9mu_PQTKvECVmJyGGRv3gV_dzapWQlefWsDvFBnZy!-402322966')])[2]</value>
      <webElementGuid>33caeb2b-91ec-48ec-a6ae-5695c6fe5cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>52ad5092-84ca-47a7-b854-848973b5d1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'registration-link' and @href = '/simple-blog/redirect/registration;jsessionid=0SAHbFgQpgS9mu_PQTKvECVmJyGGRv3gV_dzapWQlefWsDvFBnZy!-402322966' and (text() = 'Registration' or . = 'Registration')]</value>
      <webElementGuid>142880e5-9ed2-44ff-aa27-2e0dfdc6fda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/simple-blog/redirect/registration;jsessionid=BooHaJfRgmhS-pSb0zyubCIbHfjIcD93IF1nq1pbj567vjaLSHGB!-402322966')])[2]</value>
      <webElementGuid>73d44a3e-e3ae-4702-8259-07949f5ff4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'registration-link' and @href = '/simple-blog/redirect/registration;jsessionid=BooHaJfRgmhS-pSb0zyubCIbHfjIcD93IF1nq1pbj567vjaLSHGB!-402322966' and (text() = 'Registration' or . = 'Registration')]</value>
      <webElementGuid>c8c49a12-2cc6-42d5-a905-917961c4617f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
